env: "local"

server:
  address: ":8080"
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 10s

database:
  dsn: "postgresql://postgres:postgres@localhost:5432/emtest?sslmode=disable"
  sourceURL: "file:///home/pain/EMTest/migrations"