env: "local"

server:
  address: "0.0.0.0:8080"
  read_timeout: 5s
  write_timeout: 5s
  idle_timeout: 10s

database:
  dsn: postgresql://postgres:postgres@db:5432/postgres?sslmode=disable
  sourceURL: "file:///app/migrations"